### ISSUE TITLE
java.lang.NoSuchFieldError: com.google.android.gms.R$string.common_google_play_services_update_text

### ISSUE THREAD

**Issue by maklaus** [dandar3/android-google-play-services-games#1]
I used version 10.0.0 for my project with no problems.

Once upgraded to 10.2.1 I get 7/10 problem devices on Google Play Developer Console  with the same issue:

```FATAL EXCEPTION: main
 Process: com.FDGEntertainment.redball4.gp, PID: 18421
 java.lang.NoSuchFieldError: com.google.android.gms.R$string.common_google_play_services_update_text
 	at com.google.android.gms.common.internal.zzh.zzi(Unknown Source)
 	at com.google.android.gms.common.GoogleApiAvailability.zza(Unknown Source)
 	at com.google.android.gms.common.GoogleApiAvailability.getErrorDialog(Unknown Source)
 	at com.google.android.gms.common.GooglePlayServicesUtil.getErrorDialog(Unknown Source)
 	at com.FDGEntertainment.redball4.gp.GameHelper.showFailureDialog(GameHelper.java:848)
 	at com.FDGEntertainment.redball4.gp.GameHelper.showFailureDialog(GameHelper.java:815)
 	at com.FDGEntertainment.redball4.gp.GameHelper.giveUp(GameHelper.java:793)
 	at com.FDGEntertainment.redball4.gp.GameHelper.resolveConnectionResult(GameHelper.java:762)
 	at com.FDGEntertainment.redball4.gp.GameHelper.onConnectionFailed(GameHelper.java:727)
 	at com.google.android.gms.common.internal.zzm.zzn(Unknown Source)
 	at com.google.android.gms.internal.zzaat.zzc(Unknown Source)
 	at com.google.android.gms.internal.zzaar.zzf(Unknown Source)
 	at com.google.android.gms.internal.zzaar.zza(Unknown Source)
 	at com.google.android.gms.internal.zzaar$zzb$1.zzwe(Unknown Source)
 	at com.google.android.gms.internal.zzaav$zza.zzc(Unknown Source)
 	at com.google.android.gms.internal.zzaav$zzb.handleMessage(Unknown Source)
 	at android.os.Handler.dispatchMessage(Handler.java:102)
 	at android.os.Looper.loop(Looper.java:157)
 	at android.app.ActivityThread.main(ActivityThread.java:5335)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:515)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
 	at dalvik.system.NativeStart.main(Native Method)
```
I tried to search for this common_google_play_services_update_text in my projects and seems I have it:

<img width="654" alt="2017-04-18 18 03 23" src="https://cloud.githubusercontent.com/assets/5848563/25134718/5dad2ff2-2461-11e7-8547-8f804309b78c.png">

My game crashes at the first launch after a clean installation - regardless if you open the app via the "Open" button on its PlayStore page or via the app icon in your device's menu.

It seems to happen only after a new installation. I tried reseting the app data --> no crash.

The crash seems to happen only when the game was downloaded from the Google PlayStore. When you install the .apk-file directly on your device, game will launch correctly at first start.

**Comment by dandar3** [comment]
This is annoying - I believe I had similar problems with Ads and Maps libraries before, have no idea yet how it works in Android Studio, I haven't looked at it yet but I will. 

What it appears is that Google's code from a package like `base` (package `com.google.android.gms.base`) references styles or strings defined in a different package like `google-play-services-basement` (`com.google.android.gms`) as if they are local to the calling package, it won't find them and then code will crash.

What you can do is move the `common_google_play_services_update_text` string defition from `basement\res\values\values.xml` to `base` so that they get generated with the package that the code expects them. Problem is that you don't know exactly how many of these strings you need to move, it could crash for other strings.

You could decompile `google-play-services-base\libs\google-play-services-base.jar` with JD-GUI and look at `com.google.android.gms.common.internal.zzh` class to see what other strings it references. Look for getString(), I can see there are 16 matches.

```
	Line 33:       return localResources.getString(R.string.common_google_play_services_install_title);
	Line 35:       return localResources.getString(R.string.common_google_play_services_enable_title);
	Line 37:       return localResources.getString(R.string.common_google_play_services_update_title);
	Line 80:       str = paramContext.getResources().getString(R.string.common_google_play_services_notification_ticker);
	Line 93:       return localResources.getString(R.string.common_google_play_services_install_text, new Object[] { str });
	Line 95:       return localResources.getString(R.string.common_google_play_services_enable_text, new Object[] { str });
	Line 97:       return localResources.getString(R.string.common_google_play_services_updating_text, new Object[] { str });
	Line 100:         return localResources.getString(R.string.common_google_play_services_wear_update_text);
	Line 102:       return localResources.getString(R.string.common_google_play_services_update_text, new Object[] { str });
	Line 104:       return localResources.getString(R.string.common_google_play_services_unsupported_text, new Object[] { str });
	Line 116:     return localResources.getString(R.string.common_google_play_services_unknown_issue, new Object[] { str });
	Line 135:       return localResources.getString(R.string.common_google_play_services_install_button);
	Line 137:       return localResources.getString(R.string.common_google_play_services_enable_button);
	Line 139:       return localResources.getString(R.string.common_google_play_services_update_button);
	Line 141:     return localResources.getString(17039370);
	Line 164:       str = localResources.getString(R.string.common_google_play_services_unknown_issue);
```

PS: I recommend AutoDeriv plugin so that derived resources generated at build will not show up in searches unless you specifically want to. All libraries produced here support AutoDeriv through .derived config files. See more here: http://dandar3.blogspot.com/2016/09/eclipse-setting-derived-folders.html

**Comment by maklaus** [comment]
Thanks for you answer man!

I rollback Google Play Services to 10.0.0 and passed all tests fine.

Ev

**Comment by dandar3** [comment]
@maklaus 
I believe I found that Android Studio merges the Google Play Services libraries into the `basement` package, meaning they will build and run correctly regardless of which sub-project resources were defined in.

What I've done for Eclipse is I wrote a script that moves strings and declare-styleables from all Google Play Services libraries into the `basement` library (com.google.android.gms) and I think that should fix it for us.

I've rebuilt 10.2.4 libraries to include the fix, if you could take them down again and maybe release a test version in an alpha/beta channel for your users to try please and let me know how it goes - affected libraries are `ads`, `ads-lite`, `base`, `basement`, `cast`, `cast-framework`, `maps`.

https://github.com/dandar3/android-google-play-services-README/tree/10.2.4

Thanks,
Dan

**Comment by maklaus** [comment]
Hey Dan!

Thanks for your work! We've published live our app, so next update should be a year.  :( 

Ev

**Comment by dandar3** [comment]
No worries, fairly confident it should work, I'm going to push on to GPS 10.2.6 the same way, thanks for lettimg me know quickly. 

I will this close this ticket and will reopen later if necessary.
